### ISSUE TITLE
Can't fetch password from system

### ISSUE THREAD

**Issue by ccasado** [globocom/glog-cli#3]
I am getting this error with keyring option when using Python 2.7 and virtualenv:

$ glogcli -k error
Traceback (most recent call last):
  File "/Users/ccasado/Envs/glogcli/bin/glogcli", line 11, in <module>
    sys.exit(run())
  File "/Users/ccasado/Envs/glogcli/lib/python2.7/site-packages/click/core.py", line 716, in **call**
    return self.main(_args, *_kwargs)
  File "/Users/ccasado/Envs/glogcli/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/ccasado/Envs/glogcli/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, *_ctx.params)
  File "/Users/ccasado/Envs/glogcli/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(_args, **kwargs)
  File "/Users/ccasado/Envs/glogcli/lib/python2.7/site-packages/glogcli/cli.py", line 65, in run
    graylog_api = GraylogAPIFactory.get_graylog_api(cfg, environment, host, password, port, proxy, tls, username, keyring)
  File "/Users/ccasado/Envs/glogcli/lib/python2.7/site-packages/glogcli/graylog_api.py", line 257, in get_graylog_api
    password = get_password_from_keyring(gl_api.host, gl_api.username)
  File "/Users/ccasado/Envs/glogcli/lib/python2.7/site-packages/glogcli/utils.py", line 57, in get_password_from_keyring
    return keyring.get_password('glog_' + host, username)
  File "/Users/ccasado/Envs/glogcli/lib/python2.7/site-packages/keyring/core.py", line 42, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/Users/ccasado/Envs/glogcli/lib/python2.7/site-packages/keyring/backends/OS_X.py", line 44, in get_password
    return api.find_generic_password(self.keychain, service, username)
  File "/Users/ccasado/Envs/glogcli/lib/python2.7/site-packages/keyring/backends/_OS_X_API.py", line 92, in find_generic_password
    NotFound.raise_for_status(status, msg)
  File "/Users/ccasado/Envs/glogcli/lib/python2.7/site-packages/keyring/backends/_OS_X_API.py", line 43, in raise_for_status
    Error.raise_for_status(status, msg)
  File "/Users/ccasado/Envs/glogcli/lib/python2.7/site-packages/keyring/backends/_OS_X_API.py", line 35, in raise_for_status
    raise cls(status, msg)
keyring.backends._OS_X_API.Error: (-25293, "Can't fetch password from system")

**Comment by janiltonmaciel** [comment]
Essa sua issue está relacionada com outra issue do projeto de Keyring https://github.com/jaraco/keyring/issues/219

Em resumo, executa esse comando no teu python:
```
$ codesign -f -s - /path/to/virtualenv/bin/python

exemplo:  
$ codesign -f -s - /Users/janilton/.virtualenvs/logging/bin/python
```

flw

**Comment by pedrosnk** [comment]
@janiltonmaciel I would like to use it and and distribute with a cli tool. I can't afford to tell all my users to execute such command in their environments. It's possible just to downgrade the keyring dependency to `8.7`. It just works on Sierra.
